<?php
  require_once('user.php');
  require_once('course.php');
  require_once('student_course.php');
  require_once('teacher_course.php');
  require_once('attendance.php');
  require_once('announcement.php');
  require_once('material.php');
  require_once('grade.php');
  require_once('assignment.php');
?>
